### PR TITLE
Markdown help & automated docs build

### PR DESCRIPTION
**Pull request by Sup3rlativ3**
This PR adds the base markdown help files for all of the cmdlets. 

I've added ReadTheDocs support for the Markdown as per #47 ([comment](https://github.com/raandree/NTFSSecurity/issues/47#issuecomment-514998304)).

I have also included an appveyor config to allow automated build tests to confirm if the documentation is up-to-date.

Please refer to "Add-NTFSAccess.md" for what you can expect to see if this is the direction you would like to go.

Please let me know if I've done something wrong as this isn't something I do often.

### CODE REVIEW

**Comment by Sup3rlativ3** [comment]
I'll await comment from @raandree before moving to much further with this.

For reference, you can see the docs at [ReadTheDocs](https://ntfssecurity.readthedocs.io/en/latest/Cmdlets/Add-NTFSAccess/)

**Comment by AspenForester** [comment]
Thanks for contributing all that!  When this gets merged, it's going to be very helpful for folks!

**Comment by Sup3rlativ3** [comment]
Just wondering if this is going to be reviewed any time soon or should I focus my efforts elsewhere?

**Comment by raandree** [comment]
Sorry that I did not put enough attention to this module. Thank you very much for your contribution. This looks like you put a lot of time and effort into this.

**Pull request merged**
